using System.Collections.Generic;

namespace msptool
{
    public static class localisation
    {
        public static readonly Dictionary<string, Dictionary<int, string>> Msptoolhome = new()
        {
            ["GB"] = new Dictionary<int, string>
            {
                { 1, "Recycle None-Rare Clothes" },
                { 2, "Buy Boonie" },
                { 3, "Buy Animations" },
                { 4, "Buy Clothes" },
                { 5, "Buy Eyes" },
                { 6, "Buy Nose" },
                { 7, "Buy Lips" },
                { 8, "Wear RareSkin" },
                { 9, "Add to wishlist" },
                { 10, "Custom Status" },
                { 11, "Add Sponsors" },
                { 12, "Block Zac, Pixi, nova" },
                { 13, "Recycler Anything (Diamond items, clothes etc)" },
                { 14, "Wheel Spins" },
                { 15, "Lisa Hack" },
                { 16, "Automated Pixeller" },
                { 17, "Query" },
                { 18, "Username Checker" },
                { 19, "Clothes Extractor" },
                { 20, "Username To ActorId" },
                { 21, "ActorId To Username" },
                { 22, "Item Tracker" },
                { 23, "Room Thumbnail Changer" },
                { 24, "Animation Extractor" },
                { 25, "Logout" }
            },
            ["US"] = new Dictionary<int, string>
            {
                { 1, "Recycle None-Rare Clothes" },
                { 2, "Buy Boonie" },
                { 3, "Buy Animations" },
                { 4, "Buy Clothes" },
                { 5, "Buy Eyes" },
                { 6, "Buy Nose" },
                { 7, "Buy Lips" },
                { 8, "Wear RareSkin" },
                { 9, "Add to wishlist" },
                { 10, "Custom Status" },
                { 11, "Add Sponsors" },
                { 12, "Block Zac, Pixi, nova" },
                { 13, "Recycler Anything (Diamond items, clothes etc)" },
                { 14, "Wheel Spins" },
                { 15, "Lisa Hack" },
                { 16, "Automated Pixeller" },
                { 17, "Query" },
                { 18, "Username Checker" },
                { 19, "Clothes Extractor" },
                { 20, "Username To ActorId" },
                { 21, "ActorId To Username" },
                { 22, "Item Tracker" },
                { 23, "Room Thumbnail Changer" },
                { 24, "Animation Extractor" },
                { 25, "Logout" }
            },
            ["TR"] = new Dictionary<int, string>
            {
                { 1, "Nadir Olmayan Kıyafetleri Geri Dönüştür" },
                { 2, "Boonie Satın Al" },
                { 3, "Animasyon Satın Al" },
                { 4, "Kıyafet Satın Al" },
                { 5, "Göz Satın Al" },
                { 6, "Burun Satın Al" },
                { 7, "Dudak Satın Al" },
                { 8, "RareSkin Tak" },
                { 9, "İstek Listesine Ekle" },
                { 10, "Özel Durum" },
                { 11, "Sponsor Ekle" },
                { 12, "Zac, Pixi, nova'yı Engelle" },
                { 13, "Her Şeyi Geri Dönüştür (Elmas eşyalar, kıyafetler vb.)" },
                { 14, "çark çevirme" },
                { 15, "Lisa Hack" },
                { 16, "Otomatik Pixeller" },
                { 17, "hesap sorgu" },
                { 18, "Kullanıcı Adı Kontrol Edici" },
                { 19, "Kıyafet Çıkarıcı" },
                { 20, "Kullanıcı Adı ile ActorId" },
                { 21, "ActorId ile Kullanıcı Adı" },
                { 22, "Eşya Takipçisi" },
                { 23, "Oda Küçük Resim Değiştirici" },
                { 24, "Animasyon Çıkarıcı" },
                { 25, "Çıkış Yap" }
            },
            ["SE"] = new Dictionary<int, string>
            {
                { 1, "Återvinn icke-sällsynta kläder" },
                { 2, "Köp Boonie" },
                { 3, "Köp animationer" },
                { 4, "Köp kläder" },
                { 5, "Köp ögon" },
                { 6, "Köp näsa" },
                { 7, "Köp läppar" },
                { 8, "Bär RareSkin" },
                { 9, "Lägg till önskelista" },
                { 10, "Anpassad status" },
                { 11, "Lägg till sponsorer" },
                { 12, "Blockera Zac, Pixi, nova" },
                { 13, "Återvinn vad som helst (diamanter, kläder osv.)" },
                { 14, "Hjulspinn" },
                { 15, "Lisa Hack" },
                { 16, "Automatiserad Pixeller" },
                { 17, "Fråga" },
                { 18, "Användarnamnskontroll" },
                { 19, "Klädextraktör" },
                { 20, "Användarnamn till ActorId" },
                { 21, "ActorId till användarnamn" },
                { 22, "Objektspårare" },
                { 23, "Rumstumnageländrare" },
                { 24, "Animationsutvinare" },
                { 25, "Logga ut" }
            },
            ["FR"] = new Dictionary<int, string>
            {
                { 1, "Recycler des vêtements non rares" },
                { 2, "Acheter un Boonie" },
                { 3, "Acheter des animations" },
                { 4, "Acheter des vêtements" },
                { 5, "Acheter des yeux" },
                { 6, "Acheter un nez" },
                { 7, "Acheter une bouche" },
                { 8, "Acheter une peau rare" },
                { 9, "Ajouter à la liste de souhaits" },
                { 10, "Statut personnalisé" },
                { 11, "Ajouter des sponsors" },
                { 12, "Bloquer Zac, Pixi, nova" },
                { 13, "Recycler n'importe quoi (objets diamant, vêtements, etc.)" },
                { 14, "Tours de roue" },
                { 15, "Hack Lisa" },
                { 16, "Pixeller automatisé" },
                { 17, "Requête" },
                { 18, "Vérificateur de nom d'utilisateur" },
                { 19, "Extracteur de vêtements" },
                { 20, "Nom d'utilisateur vers ActorId" },
                { 21, "ActorId vers nom d'utilisateur" },
                { 22, "Suivi d'objets" },
                { 23, "Changeur de miniature de salle" },
                { 24, "Extracteur d'animations" },
                { 25, "Déconnexion" }
            },
            ["DE"] = new Dictionary<int, string>
            {
                { 1, "Nicht seltene Kleidung recyceln" },
                { 2, "Boonie kaufen" },
                { 3, "Animationen kaufen" },
                { 4, "Kleidung kaufen" },
                { 5, "Augen kaufen" },
                { 6, "Nase kaufen" },
                { 7, "Lippen kaufen" },
                { 8, "RareSkin tragen" },
                { 9, "Zur Wunschliste hinzufügen" },
                { 10, "Benutzerdefinierter Status" },
                { 11, "Sponsoren hinzufügen" },
                { 12, "Zac, Pixi, nova blockieren" },
                { 13, "Alles recyceln (Diamantgegenstände, Kleidung usw.)" },
                { 14, "Glücksraddrehungen" },
                { 15, "Lisa Hack" },
                { 16, "Automatisierter Pixeller" },
                { 17, "Abfrage" },
                { 18, "Benutzernamenprüfer" },
                { 19, "Kleidungs-Extractor" },
                { 20, "Benutzername zu ActorId" },
                { 21, "ActorId zu Benutzername" },
                { 22, "Gegenstand-Tracker" },
                { 23, "Raum-Thumbnail-Wechsler" },
                { 24, "Animations-Extractor" },
                { 25, "Abmelden" }
            },
            ["NL"] = new Dictionary<int, string>
            {
                { 1, "Recycle geen zeldzame kleding" },
                { 2, "Koop Boonie" },
                { 3, "Koop Animaties" },
                { 4, "Koop Kleding" },
                { 5, "Koop Ogen" },
                { 6, "Koop Neus" },
                { 7, "Koop Lippen" },
                { 8, "Draag RareSkin" },
                { 9, "Toevoegen aan verlanglijst" },
                { 10, "Aangepaste Status" },
                { 11, "Voeg Sponsors toe" },
                { 12, "Blokkeer Zac, Pixi, nova" },
                { 13, "Recycle Alles (Diamant items, kleding, enz.)" },
                { 14, "Wiel Spins" },
                { 15, "Lisa Hack" },
                { 16, "Geautomatiseerde Pixeller" },
                { 17, "Query" },
                { 18, "Gebruikersnaam Checker" },
                { 19, "Kleding Extractor" },
                { 20, "Gebruikersnaam naar ActorId" },
                { 21, "ActorId naar Gebruikersnaam" },
                { 22, "Item Tracker" },
                { 23, "Kamer Thumbnail Wijzig" },
                { 24, "Animatie Extractor" },
                { 25, "Uitloggen" }
            },
            ["FI"] = new Dictionary<int, string>
            {
                { 1, "Kierrätä ei-harvinaisia vaatteita" },
                { 2, "Osta Boonie" },
                { 3, "Osta animaatioita" },
                { 4, "Osta vaatteita" },
                { 5, "Osta silmät" },
                { 6, "Osta nenä" },
                { 7, "Osta huulet" },
                { 8, "Käytä RareSkin" },
                { 9, "Lisää toivelistalle" },
                { 10, "Mukautettu tila" },
                { 11, "Lisää sponsoreita" },
                { 12, "Estä Zac, Pixi, nova" },
                { 13, "Kierrätä mitä tahansa (timanttiesineet, vaatteet jne.)" },
                { 14, "Pyöräytykset" },
                { 15, "Lisa Hack" },
                { 16, "Automaattinen Pixeller" },
                { 17, "Kysely" },
                { 18, "Käyttäjänimen tarkistaja" },
                { 19, "Vaatteiden extractor" },
                { 20, "Käyttäjänimi ActorId:ksi" },
                { 21, "ActorId Käyttäjänimeksi" },
                { 22, "Esineiden seuranta" },
                { 23, "Huoneen pikkukuva vaihtaja" },
                { 24, "Animaation extractor" },
                { 25, "Kirjaudu ulos" }
            },
            ["NO"] = new Dictionary<int, string>
            {
                { 1, "Resirkuler ikke-sjeldne klær" },
                { 2, "Kjøp Boonie" },
                { 3, "Kjøp animasjoner" },
                { 4, "Kjøp klær" },
                { 5, "Kjøp øyne" },
                { 6, "Kjøp nese" },
                { 7, "Kjøp lepper" },
                { 8, "Bruk RareSkin" },
                { 9, "Legg til ønskelisten" },
                { 10, "Egendefinert status" },
                { 11, "Legg til sponsorer" },
                { 12, "Blokker Zac, Pixi, nova" },
                { 13, "Resirkuler alt (diamanter, klær osv.)" },
                { 14, "Hjulspinn" },
                { 15, "Lisa Hack" },
                { 16, "Automatisert Pixeller" },
                { 17, "Spørring" },
                { 18, "Brukernavn Sjekker" },
                { 19, "Klær Extractor" },
                { 20, "Brukernavn til ActorId" },
                { 21, "ActorId til Brukernavn" },
                { 22, "Gjenstand Tracker" },
                { 23, "Rom Miniatyr Endrer" },
                { 24, "Animasjon Extractor" },
                { 25, "Logg ut" }
            },
            ["DK"] = new Dictionary<int, string>
            {
                { 1, "Genbrug ikke-sjældne tøj" },
                { 2, "Køb Boonie" },
                { 3, "Køb animationer" },
                { 4, "Køb tøj" },
                { 5, "Køb øjne" },
                { 6, "Køb næse" },
                { 7, "Køb læber" },
                { 8, "Brug RareSkin" },
                { 9, "Tilføj til ønskeliste" },
                { 10, "Brugerdefineret status" },
                { 11, "Tilføj sponsorer" },
                { 12, "Bloker Zac, Pixi, nova" },
                { 13, "Genbrug alt (diamantgenstande, tøj osv.)" },
                { 14, "Hjulspins" },
                { 15, "Lisa Hack" },
                { 16, "Automatiseret Pixeller" },
                { 17, "Forespørgsel" },
                { 18, "Brugernavn Checker" },
                { 19, "Tøj Extractor" },
                { 20, "Brugernavn til ActorId" },
                { 21, "ActorId til Brugernavn" },
                { 22, "Genstand Tracker" },
                { 23, "Rum Thumbnail Skifter" },
                { 24, "Animations Extractor" },
                { 25, "Log ud" }
            },
            ["CA"] = new Dictionary<int, string>
            {
                { 1, "Recycler les vêtements non rares" },
                { 2, "Acheter un Boonie" },
                { 3, "Acheter des animations" },
                { 4, "Acheter des vêtements" },
                { 5, "Acheter des yeux" },
                { 6, "Acheter un nez" },
                { 7, "Acheter des lèvres" },
                { 8, "Porter RareSkin" },
                { 9, "Ajouter à la liste de souhaits" },
                { 10, "Statut personnalisé" },
                { 11, "Ajouter des commanditaires" },
                { 12, "Bloquer Zac, Pixi, nova" },
                { 13, "Recycler tout (objets diamant, vêtements, etc.)" },
                { 14, "Tours de roue" },
                { 15, "Hack Lisa" },
                { 16, "Pixeller automatisé" },
                { 17, "Requête" },
                { 18, "Vérificateur de nom d'utilisateur" },
                { 19, "Extracteur de vêtements" },
                { 20, "Nom d'utilisateur à ActorId" },
                { 21, "ActorId à nom d'utilisateur" },
                { 22, "Suivi d'objets" },
                { 23, "Changer la miniature de la salle" },
                { 24, "Extracteur d'animations" },
                { 25, "Déconnexion" }
            },
            ["AU"] = new Dictionary<int, string>
            {
                { 1, "Recycle Non-Rare Clothes" },
                { 2, "Buy Boonie" },
                { 3, "Buy Animations" },
                { 4, "Buy Clothes" },
                { 5, "Buy Eyes" },
                { 6, "Buy Nose" },
                { 7, "Buy Lips" },
                { 8, "Wear RareSkin" },
                { 9, "Add to Wishlist" },
                { 10, "Custom Status" },
                { 11, "Add Sponsors" },
                { 12, "Block Zac, Pixi, nova" },
                { 13, "Recycle Anything (Diamond Items, Clothes, etc.)" },
                { 14, "Wheel Spins" },
                { 15, "Lisa Hack" },
                { 16, "Automated Pixeller" },
                { 17, "Query" },
                { 18, "Username Checker" },
                { 19, "Clothes Extractor" },
                { 20, "Username to ActorId" },
                { 21, "ActorId to Username" },
                { 22, "Item Tracker" },
                { 23, "Room Thumbnail Changer" },
                { 24, "Animation Extractor" },
                { 25, "Logout" }
            },
            ["PL"] = new Dictionary<int, string>
            {
                { 1, "Recykling ubrań nie-rzadkich" },
                { 2, "Kup Boonie" },
                { 3, "Kup animacje" },
                { 4, "Kup ubrania" },
                { 5, "Kup oczy" },
                { 6, "Kup nos" },
                { 7, "Kup usta" },
                { 8, "Załóż RareSkin" },
                { 9, "Dodaj do listy życzeń" },
                { 10, "Niestandardowy status" },
                { 11, "Dodaj sponsorów" },
                { 12, "Zablokuj Zac, Pixi, nova" },
                { 13, "Recykling czegokolwiek (przedmioty diamentowe, ubrania itd.)" },
                { 14, "Kręcenie kołem" },
                { 15, "Hack Lisa" },
                { 16, "Automatyczny Pixeller" },
                { 17, "Zapytanie" },
                { 18, "Sprawdzacz nazwy użytkownika" },
                { 19, "Ekstraktor ubrań" },
                { 20, "Nazwa użytkownika na ID gracza" },
                { 21, "ActorID gracza na nazwe użytkownika" },
                { 22, "Śledzenie przedmiotów" },
                { 23, "Zmieniacz miniatury pokoju" },
                { 24, "Ekstraktor animacji" },
                { 25, "Wyloguj się" }
            },
            ["NZ"] = new Dictionary<int, string>
            {
                { 1, "Recycle Non-Rare Clothes" },
                { 2, "Buy Boonie" },
                { 3, "Buy Animations" },
                { 4, "Buy Clothes" },
                { 5, "Buy Eyes" },
                { 6, "Buy Nose" },
                { 7, "Buy Lips" },
                { 8, "Wear RareSkin" },
                { 9, "Add to Wishlist" },
                { 10, "Custom Status" },
                { 11, "Add Sponsors" },
                { 12, "Block Zac, Pixi, nova" },
                { 13, "Recycle Anything (Diamond Items, Clothes, etc.)" },
                { 14, "Wheel Spins" },
                { 15, "Lisa Hack" },
                { 16, "Automated Pixeller" },
                { 17, "Query" },
                { 18, "Username Checker" },
                { 19, "Clothes Extractor" },
                { 20, "Username to ActorId" },
                { 21, "ActorId to Username" },
                { 22, "Item Tracker" },
                { 23, "Room Thumbnail Changer" },
                { 24, "Animation Extractor" },
                { 25, "Logout" }
            },
            ["IE"] = new Dictionary<int, string>
            {
                { 1, "Recycle Non-Rare Clothes" },
                { 2, "Buy Boonie" },
                { 3, "Buy Animations" },
                { 4, "Buy Clothes" },
                { 5, "Buy Eyes" },
                { 6, "Buy Nose" },
                { 7, "Buy Lips" },
                { 8, "Wear RareSkin" },
                { 9, "Add to Wishlist" },
                { 10, "Custom Status" },
                { 11, "Add Sponsors" },
                { 12, "Block Zac, Pixi, nova" },
                { 13, "Recycle Anything (Diamond Items, Clothes, etc.)" },
                { 14, "Wheel Spins" },
                { 15, "Lisa Hack" },
                { 16, "Automated Pixeller" },
                { 17, "Query" },
                { 18, "Username Checker" },
                { 19, "Clothes Extractor" },
                { 20, "Username to ActorId" },
                { 21, "ActorId to Username" },
                { 22, "Item Tracker" },
                { 23, "Room Thumbnail Changer" },
                { 24, "Animation Extractor" },
                { 25, "Logout" }
            },
            ["ES"] = new Dictionary<int, string>
            {
                { 1, "Reciclar ropa no rara" },
                { 2, "Comprar Boonie" },
                { 3, "Comprar animaciones" },
                { 4, "Comprar ropa" },
                { 5, "Comprar ojos" },
                { 6, "Comprar nariz" },
                { 7, "Comprar labios" },
                { 8, "Usar RareSkin" },
                { 9, "Añadir a la lista de deseos" },
                { 10, "Estado personalizado" },
                { 11, "Añadir patrocinadores" },
                { 12, "Bloquear a Zac, Pixi, nova" },
                { 13, "Reciclar cualquier cosa (artículos de diamante, ropa, etc.)" },
                { 14, "Giros de rueda" },
                { 15, "Hack Lisa" },
                { 16, "Pixeller automatizado" },
                { 17, "Consulta" },
                { 18, "Verificador de nombre de usuario" },
                { 19, "Extractor de ropa" },
                { 20, "Nombre de usuario a ActorId" },
                { 21, "ActorId a nombre de usuario" },
                { 22, "Rastreador de objetos" },
                { 23, "Cambiar miniatura de sala" },
                { 24, "Extractor de animaciones" },
                { 25, "Cerrar sesión" }
            }
        };
    }
}
                    
