Home = [
    (1, "Recycle None-Rare Clothes"),
    (2, "Buy Boonie"),
    (3, "Buy Animations"),
    (4, "Buy Clothes"),
    (5, "Buy Eyes"),
    (6, "Buy Nose"),
    (7, "Buy Lips"),
    (8, "Wear RareSkin"),
    (9, "Add to wishlist"),
    (10, "Custom Status"),
    (11, "Add Sponsors"),
    (12, "Block Zac, Pixi, nova"),
    (13, "Recycler Anything (Diamond items, clothes etc)"),
    (14, "Wheel Spins"),
    (15, "Lisa Hack"),
    (16, "Automated Pixeller"),
    (17, "Query"),
    (18, "Username Checker"),
    (19, "Clothes Extractor"),
    (20, "Username To ActorId"),
    (21, "ActorId To Username"),
    (22, "Item Tracker"),
    (23, "Room Thumbnail Changer"),
    (24, "Animation Extractor"),
    (25, "Icon Changer"),
    (26, "Bot Generator (beta)"),
    (27, "Item Glitcher (gifter)"),
    (28, "Automated Autographer (VIP Only)"),
    (29, "starFame - Fame Farmer"),
    (30, "Password Changer"),
    (31, "Friend Requester"),
    (32, "Logout")
]