Home = [
    (1, "Buy Boonie"),
    (2, "Buy Animations"),
    (3, "Buy Clothes"),
    (4, "Buy Eyes"),
    (5, "Wear RareSkin"),
    (6, "Add to wishlist"),
    (7, "Custom Status"),
    (8, "Recycler Anything (Diamond items, clothes etc)"),
    (9, "Wheel Spins"),
    (10, "Lisa Hack"),
    (11, "Automated Pixeller"),
    (12, "Query"),
    (13, "Clothes Extractor"),
    (14, "Item Tracker"),
    (15, "Animation Extractor"),
    (16, "Bot Generator (beta)"),
    (17, "Item Glitcher (gifter)"),
    (18, "Automated Autographer (VIP Only)"),
    (19, "Logout")
]
