Home = [
    (1, "Buy Boonie"),
    (2, "Buy Animations"),
    (3, "Buy Clothes"),
    (4, "Buy Eyes"),
    (5, "Buy Nose"),
    (6, "Buy Lips"),
    (7, "Wear RareSkin"),
    (8, "Add to wishlist"),
    (9, "Custom Status"),
    (10, "Recycler Anything (Diamond items, clothes etc)"),
    (11, "Wheel Spins"),
    (12, "Lisa Hack"),
    (13, "Automated Pixeller"),
    (14, "Query"),
    (15, "Username Checker"),
    (16, "Clothes Extractor"),
    (17, "Item Tracker"),
    (18, "Room Thumbnail Changer"),
    (19, "Animation Extractor"),
    (20, "Icon Changer"),
    (21, "Bot Generator (beta)"),
    (22, "Item Glitcher (gifter)"),
    (23, "Automated Autographer (VIP Only)"),
    (24, "Logout")
]
